apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-operator
  namespace: postgres-operator
spec:
  chart:
    spec:
      chart: pgo
      sourceRef:
        kind: OCIRepository
        name: crunchydata
        namespace: flux-system
      version: 5.6
  interval: 1m0s