apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubelet-serving-cert-approver
spec:
  chart:
    spec:
      chart: kubelet-serving-cert-approver
      sourceRef:
        kind: HelmRepository
        name: j6nca
        namespace: flux-system
      version: 1.0.1
  interval: 15m
