creation_rules:
  - path_regex: .*.yaml
    encrypted_regex: ^(data|stringData)$
    age: >-
      age12m4fp9cc4mn0k3dv4sq7z98gzty5rls0aj8jmtj8ttpzs5uc7sds05p9v4,
      age1vt35hurma8s7esaurhhnlyf5lks8xsr8zht6vgpag2fj4wx7na0qd0yavj
  
  - path_regex: setup/.*.yaml
    encrypted_regex: ^key$
    age: age1vt35hurma8s7esaurhhnlyf5lks8xsr8zht6vgpag2fj4wx7na0qd0yavj

  - path_regex: setup/kubeconfig
    encrypted_regex: ^client-key-data$
    age: age1vt35hurma8s7esaurhhnlyf5lks8xsr8zht6vgpag2fj4wx7na0qd0yavj
