apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reflector
  namespace: tools
spec:
  chart:
    spec:
      chart: reflector
      sourceRef:
        kind: HelmRepository
        name: emberstack
        namespace: flux-system
      version: 7.1.262
  interval: 15m