apiVersion: v1
kind: Secret
metadata:
  name: op-credentials
  namespace: secret-ops
type: Opaque
data:
  1password-credentials.json: ENC[AES256_GCM,data:tuSww1kcZk0HSiUN6AVsHipNIFG8VN9+POUYcTuGVk/l7EDQi4XjrF324vrF/9uchWSBl2Tz1+UVm6QcDtq0CpkKs6/hpg7vOAJ73+2SsiDrZzc7zVt93pDfA/k85CsfERVeXLm6TYemJpeeA0eoSIywqpaCz9fdoB6Sgfdf6qu1DYkSkuNGLU5NviLAuo1ERuflCM9V9AKuR90plOTc0QVbvQ/arTTsuinTtZhGeHwRkEeAPeS2fWnDsvGekz1ocDv4U18WgVQIOZdIYpfQeTFqh7tVVwub31Zzypq2BWLxrz+W0PA1cqZyV/6E2D+oKozLc4IH3QmBeUq7FuposZRnH1ssWtM+AHkP77CbH8HFL3+WqhEhMyg6ReCP/6Eqymj/weRqbKR7HKjjoPsXOCdqQRiitLdVQ8FXOUm/WYZkSO0dZbJu+F65G+4bt34Vlvb8vh1GjuGSWnQuaAiZ9M3LCwBA8U3DUDpRwObd+PHzqh54KXWl7GZ7mpFoDV8tJJ0kdAa71NwX8+P3A1SZ4CC1TU/H3WuDarC6tm4fodt77ltS3bkAE3co0DDrdIVXHxatm+GUI8ywaf6gNZg3ejoZtv0tUMEx/6IqPEf98p8jeVlCaETalw2BG0KW0GoXWoNCLQA5c4+dG26TAj34zr7ZY/2PQ+KxqME38gTXr+u+upunVBb+IrVPJfVcTKDjarHne/cfug5J1P7zcGP62Iocs0rv+bzKE6Zg5FKWx6NX9jFdv2sglStC8wjJbFYQWXY+yMRR+o7Be1DzYiGzTY2aw+khIFFJkvNVIgIANs9teFYh4pDKtolijEJD9nFyilRGXfJvY+iuMJSr+wHOdFWvN1Nmpy4ZXrc1eUC8RKkHMD++C0GM8Zru5Ka/QmQ1HibH3cxNhmGJDdRnE1EFatavLv6XCaP7RoAGIXahgbAZL5ELLs5I9CgDbL8OZeq1oiUGiVu0mYM3UL9bVHs43pOcjhQ1LKONrde1dIi9Zzgrau+Qh0ppnqarzJA5Q0qAxIgUfmFyFxuv+Duq+O5zlXyTWbhhX8etreO07ZrKeozWZ7iU/Dc3sR0DDhmtzVbvcajvL/5CQOYZYzOsiLt51mny2VLXJTDn8Xcl2ZjvJ1PhhxmOAR7GpukOiZ8yb1bP/gprp4jBVv8XiArD5bD3QCnKNwyu1JHBCXqRhXeSRmvi9ViJ0nBIR5jg8SK9PisYYlmhs1LikgDW6jQoNjzmUv06oLtah10Y1vRP/Kb1OBc58SySMhbNKNSDvfuNYawLrysTnRTNYUB0zoSM1QzDFPNlgIhYzZPfs/XkhKHLQkD9Ycu5iKRVCfnxmocKxpJtCZcyLkZ3mTmjyOruNbAMcgcvVJB0DlYCAv20zXH6omXAvDY5wjyUp0bMVi+JgPwIJ3kFN7RynQnTyrF/CxUD4Cnkk4t9RtvfjWnrNDGnHbEyPNBZz2/cX3HsAL3Ox20JBYP+MgQXuanqZ963o1iD8sYJzRB78/aALle7E0ilH0rGpwWB8dIh+50dhLl2NgHpAYVmIgUfQr4pm76F1fITeGJwStMgaQoi5W9O5pOGjnLHspjg6+IfglFHcJiRA7FqZLNFbsnyG27XxkG7C0BO9ZY3TDz37jOLnCw35+VOsAtcmBONm/4N2cnsG8QL51CNCEFnzE4pVa0GaFKyOG6WJm76Fj+20VsBf6A9HT/VvrGGCVAM2tPIkMPXYQpG9UhRBZaBIwVwyqUmtKib7WMvLIobmx+FLsUgvQYneuBDxM/pEVjOgrkp9GEbB06T2H0KPGww1qL/h7QL6vHz9LAfD0CRgkElfO8WOOngFtl0mmuBelEGHLmvgGe+LaQXkyTDRktcnDanRsukzulAaqZroh5ZFrn1z00ucCRQsDqKLV67a6UMB02YYxs8GvV20xCUpZeNnGmElApSuDYx,iv:6TE+gyxYQ0neVfhRBpke+I5qeWUl4EBx1o4owmHPdJw=,tag:ERnFaKBhbQHsBL+k82lPZw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age12m4fp9cc4mn0k3dv4sq7z98gzty5rls0aj8jmtj8ttpzs5uc7sds05p9v4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4dzdTQkcyQVJ6eEJ6NWda
        T05RVFE3d1RJTEtmSi9WSjhKWW5acUNmdUdRCm51NVQvZ1dBUW5TWUd5NVU1dmQw
        STNDQVpDTmFyTHM0K2tnRlk3eHRlalkKLS0tIFJrbzBOOTRoQjA1OElmYW5TcnRp
        RHpVdjZwV2VneFdFTXA5VzVXc1ZHTU0KnfaCe7usQEiyU+WTztKl0EFIzqYJCW2n
        E0T/zatbYly9l6gi4GSA/8VaVIsDWWrpyAdA4kCdWaQI0y7WuygHWA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1vt35hurma8s7esaurhhnlyf5lks8xsr8zht6vgpag2fj4wx7na0qd0yavj
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZFJyc2NscE9kclc1ZFNQ
        Wk16MTh6RjVLbngyOVZNZ0lFNkdsRkNkM1QwCjRhdEZRVVZoOVVxeURIQWZ6Qk9X
        ektUUnNLODFwSE11Q2xqdmlhOUNsTVUKLS0tIGhJa0l0TkMzbjRuL3UwMDBlL3Zj
        aThzb2dGTHN5U1FCcmdpQ2dsZmNLdlUKdWSUQUAdhTh74WfrAhaQFijKqeJYm/Tz
        qiFJv7Tffj1No1VcBHK+P872JolPxRMAyH3CHQ7h6tvA47oLzsX4kQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-11-13T03:17:21Z"
  mac: ENC[AES256_GCM,data:6ODpIKUSt5n2/52i9zNS+k9Z4dmH4+kBz6dMtsX+693qM+ws1OB34Wrl2hcRZ83TMrTr8vD4+o8UIHJ2Kk3zuuaXa2hPQabTS2h5WKA4IedPANAr5SGTTYQltvKgA5xnaHbz8uwaBfP3qhXsO8/v/NOVYD6ZBoz84s2kpa8hu7A=,iv:4hHRjGPC65cyP3q+8+Q3N+1hJWo4oXnoCVpJA1HuggU=,tag:lL6PJtvnawnkmyvrujCuew==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.0
