apiVersion: v1
kind: Secret
metadata:
  name: op-credentials
  namespace: secret-ops
type: Opaque
data:
  1password-credentials.json: ENC[AES256_GCM,data:PjedlOFzqWXyZYYh/GqXYR+w0zooExsLqZMZ7Sr6tf+lHYpbIdh6EF0FmP7udaz28ywd8MTDCHTqWj7Cgrqff7AqgNbt544Io7UadgCii/Pz0iqN45Knjz8UH5+vEPx+T1yS3rbFXh1EHn+yb/3KFMr86ZxfueRtUOodaW3jXJols172Myw7lZUr9wQEQ29oQfepjtUoE+NWLQEJtXEDPZWjRnqs7LC+UgVrWhhzEHaIlA4tTEaqpOiI0K1ZtJRQA57/Xbon1/AE/Obx7aYpDCS0B2BteZ5/uL1gXbVtKF2wrXlVJY35x5iS9QMFUGtiRotistAhDUXndzvc2m2ouwfw9kNBBkZKtZ+8IzFEV+J9+g7BrEg4wU8fYVZgdaAQ1l5Swg4uxqtetA6ARYapIV3Yrf+EnUpYLOKeY7l6WCtM0Yk4daepOiGqq37+3T4ODiA0xLATEWxHXzZFsryKPDqQOC59csze3lm35MZGy5j9KDkMLqeb7nTaJYR3OczNcnzGdODtrEcpCBwFBUXoIz8sCj0GhySrjZeApHwbYjGZD45WnTY0BMu8OEkF9zo85GQqJzVYYoS1GG4Fe/M4fU7pi72pp/IFHPRnButlWLdebyZRQtBHax31Ge4AvK/olc7v2t1eEcKtTFw3cvtQC+RmB0SdWAD0A3UFnLBcXN1g6jotzgpZ+UjUmAoWLOw9NBIcSZu5ZYD+3oNViBGEVjj3uvttKopDD8LJIRz2UJtZQNz5at7K2Rc18aKuUddBY0pd1gUelxCTmLYUrlPLfvymJftqV9wvbocE9aEOPR8BRiAbG2PA8hCxPj+pFxNQTBeWZqpNDxu83gwnEzvGBdFY2g99tgQf9aJpU7knptaVawhEXp2ZTA2wLJb+RhS4omJmEx587nRQ5iIPaQYUCTUZ9wY5gZpfpvJiexVeTKyFurwZCpCFWbd1u7CU95OYbnqiQk5gV2Tbp8MXBdCm/9gSfqQnx1RjNFZmTKvE04SqaI4DQ2KuOSU7YzRt/LMylKdeCa3izVcl2zwznNnJpcpqevBnOyPjhN7r38JEUo1GRu0EtHNG5ifOeRVJvJUVjSWDBgX3yLBhpY7/HY1hPk7ZvMa45sdKBGvsNUA43msXTGBSAXxtNlCUP9ndRR5IFCTwV8O7mjWjfSAYR4TrbVtO1lIrkx3bQdAqld+SmY6Jt3PBLCbh5gzzXLGEF4+WFdAvC8ZD2rNZOfVL+3jgy0RtIRvMSModViSEioI6NBatKfxgKlZ8uwW18qb0uKNlL0BTD6g2/nC4zmNwcufw7B0TIMlFnnzXaQfLBnAGPZMQ3haV2mOoz0ROHG5dPKv690hByS2oIPg+tWX8Amf0n8nXKpavMoDTEhW/RJMZe8KWphsBY+XDeLWnWFcEQGdB2CNj0W8YigAV9AIuCMzpb9HZTkxCL7725ol41PmSY6JK3vB1d2glTW+E0IV4tmH3loY52ekqkBu8qnCT44DKxiH4bgI1sO8/ieQW0AI8D5BezENO1sxxyjI+Z2WInjCvD7TPYT2myQ6bdoIC2S33dr5jLmU4PX4c+i55QDGsKiYj2DtnfV/1hp/p+l6+n2A/lLhtvJzXUPJ/xgbPk55v3Ad+o+W7a5tFxgsKZ/E3izU+Ib7Z9R07wkMUdxG8V0TyUhz47JtQhPvh7oamWd6B2OPRUL8KH7TQVDGCrUX0GSHMfgp0e5FaYy9+62UeniMOyCaR0r8cS+hnQdTv4806vy7+mhXSPPeRrcdKjRd+RI4MP2PR6G7CCt544sOpTtqQkbuwIKGWETHsAbIlGsjYiVagN0chF5kYm7EQMpcx683S9x96DzGBP+Pyibz39dcKdpiezkqxu/AlKB8qsfDk6d6zwqISO1PCu7uUzacVtsABYnhpbn18sEWSKtFsHZH9JljDr8SoP51fd/joUKUaJY5HVDm3Ea4qdzHOqtYDctdqztPW4seRPgz52L9YwZneuy0Fq52h1N/37tGaFe8PrVVxtT8qS2H3u9PgKZ7Ajp1HbkiJGLGNBdu3mfBHu8kqqAzgfsK8nthYOtDEd7AJJrVomtJ+vJyDJ3HmUdO3CLxW2lL/ANoybPnmZItFTJzUf1J4PR2NJ6SZKslmaLVQMqDdTVKttGL6CIBklGScRr0AaecofeTI9d+x/vIUbDEHttG0cCrOqMjKRVM2z+aydNmeBepoyPh9egbpYll2d/7wh4so60q61RK7IYC2K8+j1itnJa8iQnVtyrVhq48swN06EfDxm68p3UcbAeo+jaDlnXpK7to9lBR/V3gdjx6/JNDAZoVBIKul7ZDW5CG+VHMaxHUNRJNicG71COeIQlbWMh4lGulhbgExReEku7/fDDc8NLAKTT5cHhm7Hbpl7admNlhck1aDQnK9zxoGL+eddnSe2BAGCRVuPy16W1jSPshoASU/EbVt8jP3aS6xKzjqXP7VV1ZZL0A/wrVZttNz8FmWwkx1dg2nnLynxI8jAkesPHfyHNmcnyl1F35n2915YysSI70Kf0x9P/FE0BJy9VqDdKi/HFv6Tikp1XK1gZ1jU3+sl9oI/M9pjKs3J3yaWA+u6kQdYhQtCWKv8KCWW6Gp5jUOGnej7xI=,iv:Ts7FgmRuQ7ODLtXV7LJGN9ast+6ygevvM7hlCamIWKk=,tag:TkNlNOlz5Fv4TWMoqVgKqA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age12m4fp9cc4mn0k3dv4sq7z98gzty5rls0aj8jmtj8ttpzs5uc7sds05p9v4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBldTB2WmRMa2ppemhZdFRW
        L0NyYWl1OTl2bnloUHMyZ0VIaDY1NTBiOWs0CjZsemx4RmN4QWF5ckt0SWp5UkRE
        WjR1OVZjRjcvWURMRzRUWlFyYjVpMFUKLS0tIGh1T1NibjZCYnVUUkJGa09VM0Zu
        bXVmNE1HL3UyQVVlSlpvKy9XRXVzc2MKpg1bXWvwBoqW7j+fvQ37MRKcR+CJEEPe
        /vZrKoywG55X+/TMBUC+euhf8045F0mlrXnX1uJLt7HC2sdoCB9Vyw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1vt35hurma8s7esaurhhnlyf5lks8xsr8zht6vgpag2fj4wx7na0qd0yavj
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBINXcxR0pySW9KSTZNQloy
        Unk2U3kydVMwZVVJOVY4MWQ2b0cwSjFuNGpRCi9mVDlCL1FPeWJGd0V4YVNTREYy
        R1l1TzdPM3JWbitPdlBrTCtxUVpCb1UKLS0tIFo0Tko5OC9NTHFsanNIckxlb1Nk
        RGc3bjlvSmJ1ZElvRDREcXR1RUxFeTQKIqo/2wvXB2sxTs98Wi82izsBEOFceNLM
        RqyaRCy8KVJrezCZJmd1GCSC6a1MT+1Ab5oeS+15owmDHyb1lSi8iw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-11-14T07:56:51Z"
  mac: ENC[AES256_GCM,data:lkRMRvwybFPQtwxxkWBgW2Wdb8znRtt6wjEBJBjh2pv2Ywfl8gJ+4uTTt/XnIrNojRHSFPZLJ66N/I7tKXNS0lYJp8wwDPYByOYEdVdFCd8ra1rFcAJAePhWAE7+1lOdHF7eSC/kt/r9djyRUwMk2vqJ4W0r2lsqOeRNH+1RKW0=,iv:LNDGh+S3KFgQumFwOiFKRdGIAV99ca84Vx+pqTrRV+E=,tag:CLmnKnNf+yYUDcJpJmsFrg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
  name: op-token
  namespace: secret-ops
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:YjLpjKpTfoKioOyk+JnrbdV5uyZW0IXOxYMqrnYATYbkNVFpHXqyjjx7Bkv02aC3N3eYwW3G9wjStk66qcPioDWDnspsDj+uhyTCScBETnqWcpgGc3K/EAewA33FhPHZqWgCb2tBg5qEhpJwgvolOEyoOYnazUGk+VGP7GWWcWwtGU+ud55wMuggXdjol3ZsYyEXgRYvyUZgRG/Ez82L3jodrKI5UYtZmyL7IjyS9EvOiohSvmKv8EeGMJEJMXH/HQDFItjao7Eh5K8GKaHbu8GXJn8Yc0dIZuesMCyHT2akMelau6UWglX8l0COq0QXxL8R/VCdxs37jIHTvz9aCnesctC0fr0O9vgooV7UyMzITs5NFjVlbZPVevb3vpOJWbcEcYuePocmr/4eg2KLD/lj04KYXQa85t0Hgzm+zHDf68lGi/35PXN0d2VvKleNmu5fxuD83s2Y7Zura/TV9YD6X7C2i2T6tDAuevaESeY5lyzjg6W+j2R0+t8Woodp3jW8Dn8OEW6RmfjQPT5IAnEkrV5TMa8M3E60A6KyycJ1x5363hoAFAAukA4UdZuNReD0uZYoHP3zVCeAbC3FARm/Ts45lithif4CWMr6foSKyUs8JehTo1+9AubG6VoN1Yp6X21qtMIIg0bF+cTxBlvh5SJfkDkqrKu+sI7mDbsK/u4bmK8qXiB9HoxANZcFsSAo2+TAzD/vXcIIDvXyYtQPCsuOmgFHMOi2W6WE66pNi+vYK8cAY3UpazJNfQxBZwp1QNntAK8s2Rbp5sWouPkYG3jcAQxMm9uKSeAUbdIrZOSMwDs9hFTFdKZ41fpddpLdmmahZyc1g817gtHf2Vmj,iv:bqSs4eqn8etSeBBabdJMPWyvrKJXPPh0KICSSI2cHNw=,tag:0cgRZmGHwE3B4XB//jKAQg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age12m4fp9cc4mn0k3dv4sq7z98gzty5rls0aj8jmtj8ttpzs5uc7sds05p9v4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBldTB2WmRMa2ppemhZdFRW
        L0NyYWl1OTl2bnloUHMyZ0VIaDY1NTBiOWs0CjZsemx4RmN4QWF5ckt0SWp5UkRE
        WjR1OVZjRjcvWURMRzRUWlFyYjVpMFUKLS0tIGh1T1NibjZCYnVUUkJGa09VM0Zu
        bXVmNE1HL3UyQVVlSlpvKy9XRXVzc2MKpg1bXWvwBoqW7j+fvQ37MRKcR+CJEEPe
        /vZrKoywG55X+/TMBUC+euhf8045F0mlrXnX1uJLt7HC2sdoCB9Vyw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1vt35hurma8s7esaurhhnlyf5lks8xsr8zht6vgpag2fj4wx7na0qd0yavj
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBINXcxR0pySW9KSTZNQloy
        Unk2U3kydVMwZVVJOVY4MWQ2b0cwSjFuNGpRCi9mVDlCL1FPeWJGd0V4YVNTREYy
        R1l1TzdPM3JWbitPdlBrTCtxUVpCb1UKLS0tIFo0Tko5OC9NTHFsanNIckxlb1Nk
        RGc3bjlvSmJ1ZElvRDREcXR1RUxFeTQKIqo/2wvXB2sxTs98Wi82izsBEOFceNLM
        RqyaRCy8KVJrezCZJmd1GCSC6a1MT+1Ab5oeS+15owmDHyb1lSi8iw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-11-14T07:56:51Z"
  mac: ENC[AES256_GCM,data:lkRMRvwybFPQtwxxkWBgW2Wdb8znRtt6wjEBJBjh2pv2Ywfl8gJ+4uTTt/XnIrNojRHSFPZLJ66N/I7tKXNS0lYJp8wwDPYByOYEdVdFCd8ra1rFcAJAePhWAE7+1lOdHF7eSC/kt/r9djyRUwMk2vqJ4W0r2lsqOeRNH+1RKW0=,iv:LNDGh+S3KFgQumFwOiFKRdGIAV99ca84Vx+pqTrRV+E=,tag:CLmnKnNf+yYUDcJpJmsFrg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.0
