apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: secret-ops
spec:
  chart:
    spec:
      chart: charts/external-secrets
      sourceRef:
        kind: GitRepository
        name: j6nca-charts
        namespace: flux-system
      version: 1.0.0
  interval: 1m0s
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: onepassword-test
  namespace: secret-ops
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect.secret-ops.svc.cluster.local:8080
      vaults:
        lab: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-token
            key: token
            namespace: secret-ops
# ---
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: onepassword-token
#   namespace: secret-ops
# spec:
#   secretStoreRef:
#     kind: SecretStore
#     name: onepassword
#   target:
#     creationPolicy: Owner
#   data:
#   - secretKey: token
#     remoteRef:
#       key: k8s-lab-onepassword-token
#       property: credential
# ---
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: op-credentials
#   namespace: secret-ops
# spec:
#   secretStoreRef:
#     kind: SecretStore
#     name: onepassword
#   target:
#     creationPolicy: Owner
#   data:
#   - secretKey: 1password-credentials.json
#     remoteRef:
#       key: k8s-lab-op-credentials
#       property: 1password-credentials.json
