apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: 8.0.2
  interval: 1m0s
  values:
    grafana.ini:
      server:
        # domain: helm-testing-grafana
        # root_url: "%(protocol)s://%(domain)s/grafana/"
        # serve_from_sub_path: true
      feature_toggles:
        enable: externalServiceAccounts
    persistence:
      enabled: true
    # Disable psp as PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
    rbac:
      pspEnabled: false
    plugins:
      - grafana-oncall-app
    extraVolumes:
      - name: provisioning
        configMap:
          name: helm-testing-grafana-plugin-provisioning
    extraVolumeMounts:
      - name: provisioning
        mountPath: /etc/grafana/provisioning/plugins/grafana-oncall-app-provisioning.yaml
        subPath: grafana-oncall-app-provisioning.yaml
    # admin:
    #   existingSecret: grafana-admin
    #   userKey: admin-user
    #   passwordKey: admin-password
    # extraLabels:
    #   <<: *metadata
    # podLabels:
    #   <<: *metadata
    plugins:
      - grafana-oncall-app
