apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sops-gpg
  namespace: secret-ops
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner

    # this is how the Kind=Secret will look like
    template:
      data:
        # multiline string
        sops.asc: |-
          {
            "AccountTag": "{{ .account_id | toString }}",
            "TunnelID": "{{ .tunnel_id | toString }}",
            "TunnelSecret": "{{ .tunnel_secret | toString }}"
          }

  data:
  - secretKey: account_id
    remoteRef:
      key: cloudflared-tunnel-credentials
      property: account-id
  - secretKey: tunnel_id
    remoteRef:
      key: cloudflared-tunnel-credentials
      property: tunnel-id
  - secretKey: tunnel_secret
    remoteRef:
      key: cloudflared-tunnel-credentials
      property: tunnel-secret