apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pi-hole
  namespace: network
spec:
  chart:
    spec:
      chart: charts/pi-hole
      sourceRef:
        kind: GitRepository
        name: j6nca-charts
        namespace: flux-system
      version: 4.10.1
  interval: 1m0s
