apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oncall
  namespace: oncall
spec:
  chart:
    spec:
      chart: oncall
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: 1.7.2
  interval: 15m
  values:
    grafana:
      enabled: false
    externalGrafana:
      url: http://grafana.grafana.svc.cluster.local:3000
    ingress-nginx:
      enabled: false
    cert-manager:
      enabled: false
    ingress:
      enabled: false
    # use postgres chart here for testing since we will likely use that as the external backend
    database:
      type: postgresql
    mariadb:
      enabled: false
    postgresql:
      enabled: true
      # auth:
      #   existingSecret: oncall-postgres-admin
    # engine:
    #   podLabels:
    #     <<: *metadata
