apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-operator
  namespace: grafana
spec:
  chartRef:
    kind: OCIRepository
    name: grafana
    namespace: flux-system
  version: "v5.13.0"
  interval: 1m0s
