apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homepage
  namespace: tools
spec:
  chart:
    spec:
      chart: homepage
      sourceRef:
        kind: HelmRepository
        name: j6nca
        namespace: flux-system
      version: 1.3.0
  interval: 15m
  values:
    metadata:
      service: homepage
      environment: local
      managedBy: fluxcd
    config:
      kubernetes:
        mode: cluster
      settings:
        title: My homelab homepage
        layout:
          Media:
            style: row
            columns: 4
      custom_css: ""
      custom_js: ""
      bookmarks:
        - Sites:
            - Blog:
                - icon: mkdocs.svg
                  href: https://notes.j6n.ca
            - Github:
                - icon: github.svg
                  href: https://github.com/j6nca
      services:
        - Media:
            - Jellyfin:
                href: https://watch.j6n.ca
                icon: jellyfin.svg
                # widget:
                #   type: jellyfin
                #   url: https://watch.j6n.ca
                #   key: apikeyapikeyapikeyapikeyapikey
                #   enableBlocks: true
                #   enableNowPlaying: true
            - Jellyseer:
                href: https://jellyseer.j6n.ca
                icon: jellyseerr.svg
                # widget:
                #   type: jellyseer
                #   url: https://jellyseer.j6n.ca
                #   key: apikeyapikeyapikeyapikeyapikey
            - Sonarr:
                href: https://watch.j6n.ca
                icon: sonarr.svg
                # widget:
                #   type: sonarr
                #   url: https://watch.j6n.ca
                #   key: apikeyapikeyapikeyapikeyapikey
            - Radarr:
                href: https://watch.j6n.ca
                icon: radarr.svg
                # widget:
                #   type: radarr
                #   url: https://watch.j6n.ca
                #   key: apikeyapikeyapikeyapikeyapikey
        - Networking:
            - PiHole:
                href: http://localhost/
                icon: pi-hole.svg
                # widget:
                #   type: pihole
                #   url: http://pi.hole.or.ip
                #   key: yourpiholeapikey # optional
            - OPNSense:
                href: http://localhost/
                icon: opnsense.svg
                # widget:
                #   type: opnsense
                #   url: http://opnsense.host.or.ip
                #   username: key
                #   password: secret
        - Monitoring:
            - Gatus:
                href: http://localhost/
                icon: gatus.svg
            - Grafana:
                href: http://localhost/
                icon: grafana.svg
                # widget:
                #   type: grafana
                #   url: http://grafana.host.or.ip:port
                #   username: username
                #   password: password
            - Kube-Ops-View:
                href: http://localhost/
                icon: kubernetes.svg
        - Gaming:
            - Pterodactyl:
                href: http://localhost/
                icon: pterodactyl.svg
        - Tools:
            - Actual:
                href: http://localhost/
                icon: actual.png
            - Yopass:
                href: http://localhost/
                icon: https://yopass.se/yopass.svg
            - IT-Tools:
                href: http://localhost/
                icon: kubernetes.svg
      widgets:
        - kubernetes:
            cluster:
              show: true
              cpu: true
              memory: true
              showLabel: true
              label: "cluster"
            nodes:
              show: true
              cpu: true
              memory: true
              showLabel: true
        - resources:
            backend: resources
            expanded: true
            cpu: true
            memory: true
        - search:
            provider: duckduckgo
            target: _blank
      docker: ""