---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: onepassword-connect
  namespace: flux-system
spec:
  targetNamespace: secret-ops
  commonMetadata:
    labels:
      app.kubernetes.io/name: onepassword-connect
  path: ./fluxcd/clusters/lab/apps/secret-ops/onepassword-connect/app
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  interval: 10m
  retryInterval: 1m
  timeout: 5m
