apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  chart:
    spec:
      chart: cilium
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      version: 1.14.0
  interval: 1m0s
  values:
    ipam:
      mode: "kubernetes"
    kubeProxyReplacement: "disabled"
    cgroup:
      autoMount:
        enabled: false
      hostRoot: /sys/fs/cgroup
    operator:
      replicas: 1
    hubble:
      relay:
        enabled: true
      ui:
        enabled: true
    hostFirewall:
      enabled: true
