apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: goldpinger
  namespace: monitoring
spec:
  chart:
    spec:
      chart: goldpinger
      sourceRef:
        kind: GitRepository
        name: j6nca
        namespace: flux-system
      version: 1.0.0
  interval: 1m0s
