apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
spec:
  chart:
    spec:
      chart: metrics-server
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: flux-system
      version: 3.12.1
  interval: 15m
  values:
    metrics-server:
      apiService:
        insecureSkipTLSVerify: false
      tls:
        type: cert-manager 
