---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: onepassword
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect.secret-ops.svc.cluster.local:8080
      vaults:
        lab: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-token
            key: token
            namespace: secret-ops
