apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: renovate-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    # this is how the Kind=Secret will look like
    template:
      data:
        RENOVATE_TOKEN: { { .token | toString } }

  data:
    - secretKey: token
      remoteRef:
        key: renovate-pat
        property: token
