apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: renovate
  namespace: cicd
spec:
  chart:
    spec:
      chart: renovate
      sourceRef:
        kind: HelmRepository
        name: j6nca
        namespace: flux-system
      version: 1.0.0
  interval: 1m0s
  values:
    renovate:
      renovate:
        existingSecret: renovate-config
        config: |
          {
            "platform": "github",
            "autodiscover": "false",
            "repositories": ["j6nca/helm-charts"]
          }
