apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: spegel
  namespace: spegel
spec:
  chartRef:
    kind: OCIRepository
    name: spegel
    namespace: flux-system
  interval: 1m0s
  values:
    spegel:
      containerdRegistryConfigPath: /etc/cri/conf.d/hosts
