apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: spegel
spec:
  chartRef:
    kind: OCIRepository
    name: spegel
    namespace: flux-system
  interval: 15m
  values:
    spegel:
      containerdRegistryConfigPath: /etc/cri/conf.d/hosts
