apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lgtm-stack
  namespace: observability
spec:
  chart:
    spec:
      chart: charts/lgtm-stack
      sourceRef:
        kind: GitRepository
        name: j6nca-charts
        namespace: flux-system
      version: 1.0.0
  interval: 1m0s
  dependsOn:
    - name: external-secrets
      namespace: secret-ops
