---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: renovate
  namespace: flux-system
spec:
  targetNamespace: cicd
  commonMetadata:
    labels:
      app.kubernetes.io/name: renovate
  path: ./fluxcd/clusters/lab/apps/cicd/renovate/app
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  interval: 10m
  retryInterval: 1m
  timeout: 5m
