apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudflare-tunnel
  namespace: network
spec:
  chart:
    spec:
      chart: cloudflare-tunnel
      sourceRef:
        kind: HelmRepository
        name: cloudflare
        namespace: flux-system
      version: 0.3.0
  interval: 1m0s
  dependsOn:
    - name: external-secrets
      namespace: secret-ops
  values:
    cloudflare-tunnel:
      cloudflare:
        secretName: cloudflared-tunnel-credentials
      replicaCount: 1
