apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudflare-tunnel
  namespace: network
spec:
  chart:
    spec:
      chart: charts/cloudflare-tunnel
      sourceRef:
        kind: GitRepository
        name: j6nca-charts
        namespace: flux-system
      version: 1.0.0
  interval: 1m0s
  values:
    cloudflare:
      secretName: cloudflared-tunnel-token
