apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: network
spec:
  chart:
    spec:
      chart: external-dns
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
      version: 1.14.5
  interval: 1m0s
  dependsOn:
    - name: external-secrets
      namespace: secret-ops
  values:
    provider: cloudflare
      domainFilters:
      - j6n.ca
      env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: cloudflare-dns
            key: token
