---
apiVersion: v1
kind: Namespace
metadata:
  name: network
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latests
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
