apiVersion: v1
kind: Secret
metadata:
  name: blahblahblahtest
  namespace: network
stringData:
  credentials.json: |-
    {
      "AccountTag": "blah",
      "TunnelID": "blah",
      "TunnelSecret": "blah"
    }
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflared-tunnel-credentials
  namespace: network
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner

    # this is how the Kind=Secret will look like
    template:
      type: kubernetes.io/tls
      data:
        # multiline string
        credentials.json: |-
          {
            "AccountTag": "{{ .account_id | toString }}",
            "TunnelID": "{{ .tunnel_id | toString }}",
            "TunnelSecret": "{{ .tunnel_secret | toString }}"
          }

  data:
  - secretKey: account_id
    remoteRef:
      key: cloudflared-tunnel-credentials
      property: account-id
  - secretKey: tunnel_id
    remoteRef:
      key: cloudflared-tunnel-credentials
      property: tunnel-id
  - secretKey: tunnel_secret
    remoteRef:
      key: cloudflared-tunnel-credentials
      property: tunnel-secret
