apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflared-tunnel-token
  namespace: secret-ops
spec:
  secretStoreRef:
    kind: SecretStore
    name: onepassword
  target:
    creationPolicy: Owner
  data:
  - secretKey: token
    remoteRef:
      key: cloudflared-tunnel-token
      property: credential