apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflared-tunnel-credentials
  namespace: network
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
  data:
  - secretKey: account-id
    remoteRef:
      key: cloudflared-tunnel-credentials
      property: account-id
  - secretKey: tunnel-id
    remoteRef:
      key: cloudflared-tunnel-credentials
      property: tunnel-id
  - secretKey: tunnel-secret
    remoteRef:
      key: cloudflared-tunnel-credentials
      property: tunnel-secret
