---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudflare-tunnel
  namespace: flux-system
spec:
  targetNamespace: cloudflare-tunnel
  commonMetadata:
    labels:
      app.kubernetes.io/name: cloudflare-tunnel
  path: ./fluxcd/clusters/lab/apps/cloudflare-tunnel/cloudflare-tunnel/app
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  interval: 10m
  retryInterval: 1m
  timeout: 5m
