apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: secret-ops
spec:
  chart:
    spec:
      chart: external-secrets
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
      version: 0.9.19
  interval: 1m0s
  dependsOn:
    - name: onepassword-connect
---
# apiVersion: external-secrets.io/v1beta1
# kind: ClusterSecretStore
# metadata:
#   name: onepassword
#   namespace: secret-ops
# spec:
#   provider:
#     onepassword:
#       connectHost: http://onepassword-connect.secret-ops.svc.cluster.local:8080
#       vaults:
#         lab: 1
#       auth:
#         secretRef:
#           connectTokenSecretRef:
#             name: onepassword-token
#             key: token
#             namespace: secret-ops
