apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: onepassword-connect
  namespace: secret-ops
spec:
  chart:
    spec:
      chart: connect
      sourceRef:
        kind: HelmRepository
        name: onepassword
        namespace: flux-system
      version: 1.15.0
  interval: 1m0s
