apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana-oncall
  namespace: monitoring
spec:
  chart:
    spec:
      chart: oncall
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: 1.7.2
  interval: 1m0s
