apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: discord-webhook
  namespace: alerts
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner

  data:
  - secretKey: discord-webhook
    remoteRef:
      key: fluxcd-discord-webhook
      property: password
