---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: spegel
  namespace: flux-system
spec:
  targetNamespace: spegel
  commonMetadata:
    labels:
      app.kubernetes.io/name: spegel
  path: ./fluxcd/clusters/lab/apps/spegel/spegel/app
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  interval: 10m
  retryInterval: 1m
  timeout: 5m
