apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gatus
  namespace: monitoring
spec:
  chart:
    spec:
      chart: gatus
      sourceRef:
        kind: HelmRepository
        name: minicloudlabs
        namespace: flux-system
      version: 3.4.5
  interval: 1m0s
  values:
    config:
      endpoints:
        - name: kube-ops-view
          group: tools
          url: http://kube-ops-view.tools.svc.cluster.local:80
          conditions:
            - '[STATUS] == 200'
          interval: 5m
        - name: grafana
          group: monitoring
          url: http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local:80
          conditions:
            - '[STATUS] == 200'
          interval: 5m
        - name: prometheus
          group: monitoring
          url: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
          conditions:
            - '[STATUS] == 200'
          interval: 5m
